#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_holo_data.py - hardpoint data for the holo viewer, generated not pasted.

Reads the derived hardpoints and the model library that actually exists, and
emits testing/_src/holo_data.gen.js. Same pattern as build_keybind_modes.py and
build_kb_actions.py: one writer, no second copy of the data.

WHAT THIS SCRIPT WILL NOT DO: GUESS WHICH HULL A HARDPOINT SET BELONGS TO

hardpoints.json is keyed by full names with manufacturers - "Drake Cutlass
Black". The model library is keyed by the ship folder name - "Cutlass Black
Best In Show Edition 2949". Matching those is mostly obvious and occasionally a
judgement, and the judgement is where a wrong answer would be invisible: markers
drawn on the wrong airframe still look like markers.

So the match is EXACT-SUFFIX ONLY, after stripping a known manufacturer prefix.
Anything that does not match exactly is reported as unmatched and carries no
model. It is NOT silently attached to a lookalike.

As of 2026-08-09 that leaves two of the four unmatched, and both are real gaps
in the model library rather than naming problems:

    Aegis Sabre               -> Sabre.glb            8 hardpoints, displayable
    Tumbril Cyclone           -> Cyclone.glb          0 hardpoints, displayable
    Drake Cutlass Black       -> NO MODEL            15 hardpoints, cannot show
    RSI Constellation Aquila  -> NO MODEL            12 hardpoints, cannot show

Neither the base Cutlass Black nor the Constellation Aquila exists in the 235
model library or in sc-ships/ - checked directly, they are absent, not
mis-deployed. The Cutlass Black Best In Show Edition 2949 is present and is
plausibly the same airframe, but "plausibly the same airframe" is exactly the
sort of assumption this project does not let a script make on its own. If Sleven
confirms the hull is identical, add it to MANUAL_MATCHES below and it lights up.
"""

import glob
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
HP = os.path.join(HERE, "data-layerrawhardpoints", "hardpoints.json")
MODELS = os.path.join(HERE, "testing", "_deploy", "models")
OUT = os.path.join(HERE, "testing", "_src", "holo_data.gen.js")

# Manufacturer words that prefix a hardpoints.json key but never a model name.
MAKERS = ("Drake", "RSI", "Aegis", "Tumbril", "Anvil", "Origin", "MISC",
          "Crusader", "Consolidated Outland", "Esperia", "Argo", "Banu",
          "Aopoa", "Kruger", "Gatac", "Mirai", "Greycat", "Vanduul")

# Deliberate, human-confirmed equivalences. EMPTY BY DEFAULT - an entry here is
# somebody stating that two names are the same airframe, which is a claim about
# the world that a script cannot check.
MANUAL_MATCHES = {}


def model_key(name):
    """_deploy/models uses the CC_SAFE convention: non-alphanumerics -> _."""
    return re.sub(r"[^A-Za-z0-9._-]+", "_", name)


def main():
    with open(HP, "r", encoding="utf-8") as fh:
        hardpoints = json.load(fh)

    available = {os.path.splitext(os.path.basename(p))[0]
                 for p in glob.glob(os.path.join(MODELS, "*.glb"))}

    ships, unmatched = {}, []
    for full_name, points in hardpoints.items():
        bare = full_name
        for m in MAKERS:
            if bare.startswith(m + " "):
                bare = bare[len(m) + 1:]
                break
        candidate = MANUAL_MATCHES.get(full_name, bare)
        key = model_key(candidate)
        if key not in available:
            unmatched.append((full_name, bare, len(points)))
            continue
        ships[full_name] = {
            "model": key + ".glb",
            "display": bare,
            "points": points,
        }

    out = [
        "/* GENERATED by build_holo_data.py - do not hand edit.",
        "   Sources: data-layerrawhardpoints/hardpoints.json and the .glb files",
        "   actually present in _deploy/models/.",
        "",
        "   HOLO_UNMATCHED lists hardpoint sets with no model in the library. They",
        "   are carried through DELIBERATELY rather than dropped, so the page can",
        "   say what it cannot show instead of quietly showing less. */",
        "",
        "const HOLO_SHIPS=%s;" % json.dumps(ships, separators=(",", ":"), sort_keys=True),
        "const HOLO_UNMATCHED=%s;" % json.dumps(
            [{"name": n, "bare": b, "count": c} for n, b, c in unmatched],
            separators=(",", ":")),
        "/* Every position in HOLO_SHIPS is DERIVED. CIG's own position field is",
        "   null for all 53,651 mounts - see FINDING_fixed-hardpoints-derived. */",
        "const HOLO_DERIVED_NOTE=%s;" % json.dumps(
            "Positions are derived from the ship's own geometry and port naming, "
            "not read from the game files. CIG's position field is null for all "
            "53,651 mounts, so there is nothing authoritative to read. Treat these "
            "as close, not exact."),
        "",
    ]
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(out))

    print("wrote %s" % os.path.relpath(OUT, HERE))
    for name, s in sorted(ships.items()):
        print("  %-30s -> %-34s %2d hardpoints" % (name, s["model"], len(s["points"])))
    for name, bare, n in unmatched:
        print("  %-30s -> NO MODEL IN LIBRARY (%r)   %2d hardpoints NOT displayable"
              % (name, bare, n))
    print()
    print("  displayable: %d of %d hardpoint sets"
          % (len(ships), len(ships) + len(unmatched)))


if __name__ == "__main__":
    main()
