#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_hardpoint_join.py - the 29 ships whose hardpoints were already on disk.

    order    "29 SHIPS ALREADY HAVE THEIR HARDPOINTS. JOIN THE NAMES."
    finding  docs/FINDING_68-ships-without-hardpoints-2026-08-16.md (C3)
    rulings  DECISION_hull-configuration-acquisition-2026-08-16.md
             DECISION_shared-hulls-are-fine-unless-the-shape-differs

68 ships render as bare hulls. 27 of them are genuinely missing data. 29 have
every mount already extracted - 213 of them - under a key that does not join to
the model filename. This joins those names, places the markers, and refuses any
pair it cannot stand behind.

TWO CAUSES, TWO DIFFERENT ANSWERS
=================================

**E1 - the model file uses a short name and the mount data uses CIG's full one.**
Aurora_CL against "Aurora Mk I CL". A2_Hercules against "A2 Hercules
Starlifter". There is no rule to derive one from the other - "Starlifter" is not
in the filename and never will be - so this is a MAPPING, written down, twelve
lines, each one checked.

**E2 - the model is a paint or an edition and the mounts live under the base
hull.** This is NOT a mapping and must never become one. Sleven ruled today that
a paint or an edition is a CONFIGURATION of a hull, and the shared-hull ruling
before it established that the same hull has the same hardpoints. So an edition
resolves to its base BY RULE:

    the base is the LONGEST mount-data key whose words all appear, in order,
    inside the model's name

    Caterpillar_Best_In_Show_Edition_2949  ->  Caterpillar
    Carrack_Expedition_w_C8X               ->  Carrack Expedition   (not Carrack:
                                               longer wins, so a variant is not
                                               swallowed by its own base)
    F7C-M_Super_Hornet_Heartseeker_Mk_I    ->  F7C-M Super Hornet Mk I
                                               (an inserted word, which a
                                               drop-the-tail rule would miss)

The next Best In Show edition and every future Wikelo livery resolve with no
line added anywhere. That is the whole point, and it is tested by feeding this a
fabricated edition name that has never existed.

THE TRAP, AND WHAT IS DONE ABOUT IT
===================================

A wrong mapping is worse than a missing one. A bare hull is visibly incomplete;
a Gladius wearing a Hammerhead's hardpoints looks authoritative and is a lie.
This project already has the standing case: "Ares Inferno" and "Starfighter
Inferno" share one word and ARE the same ship, while similar names elsewhere are
not. Name similarity is not identity.

So nothing is placed on a name alone. Every pair must also survive:

  1. THE SHAPE CHECK. The model's own proportions are matched against the
     published dimensions of the ship it resolved to, by the same
     `resolve_frame` guard that refused 7 ships in the original run.

     **AND IT IS NOT ENOUGH ON ITS OWN.** I wrote here that a Gladius hull
     against Hammerhead dimensions "is not close", then measured it: err 0.11,
     comfortably inside the 0.35 threshold. It compares SHAPE and is deliberately
     blind to size, because the model library mixes metres, centimetres and
     normalised units - and a scale band cannot rescue it either, because 19 of
     the 167 placed ships legitimately sit between 0.2 and 0.8 units per metre.
     The check the order asks for is check 3.

  2. THE MOUNT CHECK, where it can be run. Some editions carry their own mount
     record as well as their base ("A2 Hercules Starlifter Wikelo War Special").
     Where both exist, the COUNT and the NAMES must agree, or the pair is
     refused and reported rather than rendered.

  3. THE HULL CHECK - the one that can actually tell a Gladius from a
     Hammerhead. An edition is the same mesh with a different skin, so its
     bounding box must match the BASE HULL'S OWN MODEL to within 2%. That is a
     comparison between two things we hold rather than between a model and a
     number. It runs on 9 of the 16 rule-resolved pairs; for the other 7 the base
     hull has no model on disk, and that is reported as NOT PERFORMED rather than
     counted as a pass.

Everything refused is listed in the report with its reason. Nothing is dropped
silently.

WHY THE PLACEMENT IS RE-IMPLEMENTED HERE
========================================

`place_fleet.py` is C3's and it is the one writer of `hardpoints_fleet.json`.
It ran in a cloud sandbox against `/home/claude/fleet/geo` - geometry that is
not in this repo and cannot be regenerated by it - and it needs numpy, which is
not installed on this machine and which nothing here may install without asking.

So this carries a pure-Python port of the placement rules and writes a SEPARATE
file. Two writers on one artifact is the defect this project has paid for three
times; `hardpoints_fleet.json` keeps its single writer and the viewer reads both
datasets.

**The port is checked against the original rather than trusted.** `--verify`
places a ship that C3 already placed and compares, so a port that had drifted
would be caught by disagreeing with the file it is meant to match.

Rule 15: encodings stated.
"""

import io
import json
import math
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
HOLO = os.path.join(HERE, "data-layer", "derived", "holo-hardpoints")
MOUNTS = os.path.join(HOLO, "ship_mounts.json")
FLEET = os.path.join(HOLO, "hardpoints_fleet.json")
MODELS = os.path.join(HERE, "testing", "_deploy", "models")

OUTDIR = os.path.join(HERE, "data-layer", "derived", "holo-hardpoints-join")
OUT = os.path.join(OUTDIR, "hardpoints_join.json")
REPORT = os.path.join(OUTDIR, "join_report.json")
MANIFEST = os.path.join(OUTDIR, "MANIFEST.json")

# Where decode_glb_points.js put the vertex data. Not in the repo: it is 30 MB
# of derived geometry that can be regenerated from the models in seconds.
GEO = os.environ.get("CC_GEO_DIR", "")

# E1 - THE TWELVE THAT NEED A NAME WRITTEN DOWN.
#
# Each of these is a model whose file name is a shortening of the ship's real
# name, with a word that appears nowhere in the file: Starlifter, Interceptor,
# Rescue, "Mk I". No rule derives them, so they are listed - and each still has
# to pass the shape check below like everything else.
E1 = {
    "Aurora_CL": "Aurora Mk I CL",
    "Aurora_ES": "Aurora Mk I ES",
    "Aurora_LN": "Aurora Mk I LN",
    "Aurora_LX": "Aurora Mk I LX",
    "Aurora_MR": "Aurora Mk I MR",
    "A2_Hercules": "A2 Hercules Starlifter",
    "C2_Hercules": "C2 Hercules Starlifter",
    "M2_Hercules": "M2 Hercules Starlifter",
    "600i_Explorer": "600i",
    "Mercury": "Mercury Star Runner",
    "M50": "M50 Interceptor",
    "C8R_Pisces": "C8R Pisces Rescue",
    # E3 in the finding, and it is the same kind of thing: one character.
    # Khartu-Al.glb against the mount key "Khartu-al". A capital A cost a whole
    # ship, 5 mounts and 1,635 pilot DPS.
    "Khartu-Al": "Khartu-al",
}

KIND = {"Turret": "mount", "MissileLauncher": "missile",
        "WeaponDefensive": "countermeasure", "WeaponGun": "gun",
        "TurretBase": "mount"}


def say(line):
    sys.stdout.buffer.write((line + "\n").encode("utf-8", "backslashreplace"))


def read_json(path, what):
    if not os.path.exists(path):
        sys.exit("MISSING INPUT: %s\n(%s)\nNothing was written." % (path, what))
    with io.open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


# ==========================================================================
# the placement rules, ported from place_fleet.py without numpy
# ==========================================================================

def tokens(s):
    return re.sub(r"[^a-z0-9]+", " ", str(s).lower()).split()


def read_location(where, port):
    t = tokens(where) + tokens(port)
    loc = {"side": None, "vert": None, "lon": None, "part": None, "index": None}
    if "left" in t or "port" in t:
        loc["side"] = "left"
    if "right" in t or "starboard" in t:
        loc["side"] = "right"
    if any(w in t for w in ("top", "upper", "dorsal")):
        loc["vert"] = "top"
    if any(w in t for w in ("bottom", "lower", "belly", "ventral", "under")):
        loc["vert"] = "bottom"
    if any(w in t for w in ("nose", "front", "fwd", "forward")):
        loc["lon"] = "front"
    if any(w in t for w in ("rear", "aft", "back", "tail")):
        loc["lon"] = "rear"
    if "mid" in t or "middle" in t:
        loc["lon"] = "mid"
    for part in ("wing", "pylon", "nose", "body", "hull", "turret",
                 "missilerack", "tractor", "chin", "roof", "canopy"):
        if part in t:
            loc["part"] = part
            break
    if loc["part"] is None:
        if "missile" in t and "rack" in t:
            loc["part"] = "missilerack"
        elif "countermeasure" in t or "cm" in t:
            loc["part"] = "countermeasure"
        elif "gun" in t or "weapon" in t or "laser" in t:
            loc["part"] = "gun"
    for w in t:
        if w.isdigit():
            loc["index"] = int(w)
            break
    return loc


TARGET = {
    "nose": (0.18, 0.50, 0.07), "chin": (0.16, 0.16, 0.16),
    "canopy": (0.14, 0.85, 0.26), "roof": (0.14, 0.92, 0.42),
    "wing": (0.88, 0.46, 0.52), "pylon": (0.72, 0.30, 0.56),
    "body": (0.34, 0.46, 0.44), "hull": (0.34, 0.46, 0.44),
    "turret": (0.16, 0.88, 0.46), "missilerack": (0.56, 0.62, 0.46),
    "countermeasure": (0.62, 0.44, 0.80), "tractor": (0.12, 0.20, 0.52),
    "gun": (0.62, 0.50, 0.36), None: (0.50, 0.50, 0.44),
}
LON_SHIFT = {"front": -0.18, "rear": 0.18, "mid": 0.0, None: 0.0}


def clip(v, lo, hi):
    return lo if v < lo else (hi if v > hi else v)


def target_uvw(loc, spread=0.0):
    u, v, w = TARGET[loc["part"] if loc["part"] in TARGET else None]
    u = -u if loc["side"] == "left" else (u if loc["side"] == "right" else 0.0)
    if loc["vert"] == "top":
        v = max(v, 0.86)
    elif loc["vert"] == "bottom":
        v = min(v, 0.14)
    w += LON_SHIFT[loc["lon"]] + spread
    if loc["index"]:
        w += (loc["index"] - 1) * 0.13 - 0.13
    return u, clip(v, 0.02, 0.98), clip(w, 0.02, 0.98)


def resolve_frame(mn, mx, dim):
    """Which bbox axis is length, width, height - decided on SHAPE, not size.

    Ported unchanged. The model library is not consistently scaled (metres,
    centimetres and normalised all appear), so proportions decide the axes and
    the scale is measured afterwards. A ship whose proportions do not match its
    own spec sheet is refused - which is exactly the guard that makes a wrong
    name mapping fail here instead of on a page.
    """
    ext = [mx[i] - mn[i] for i in range(3)]
    want = {"length": dim.get("length"), "width": dim.get("width"),
            "height": dim.get("height")}
    if not all(want.values()):
        return None, "no published dimensions", None
    if min(ext) <= 0:
        return None, "degenerate hull %r" % (ext,), None

    wn = [want["length"], want["width"], want["height"]]
    wmax = max(wn)
    wr = [x / float(wmax) for x in wn]

    best, best_err = None, 1e9
    emax = max(ext)
    for lat in range(3):
        for up in range(3):
            for lon in range(3):
                if len({lat, up, lon}) != 3:
                    continue
                er = [ext[lon] / emax, ext[lat] / emax, ext[up] / emax]
                err = sum(abs(er[i] - wr[i]) for i in range(3))
                if err < best_err:
                    best_err, best = err, (lat, up, lon)

    if best_err > 0.35:
        return None, ("proportions do not match published dims (err %.2f, ext %s, "
                      "want %s)" % (best_err, [round(e, 2) for e in ext], wn)), None

    scale = ext[best[2]] / float(want["length"])
    return best, best_err, scale


def nose_sign(pts, ix_len, ix_lat, ix_up):
    """Which end of the length axis is the nose. The tail is wide; the nose is
    narrow. Measured, never assumed."""
    n = len(pts) // 3
    zs = [pts[i * 3 + ix_len] for i in range(n)]
    lo, hi = min(zs), max(zs)
    span = hi - lo
    if span <= 0:
        return -1
    a_lat, a_up, b_lat, b_up = [], [], [], []
    for i in range(n):
        z = zs[i]
        if z <= lo + span * 0.15:
            a_lat.append(pts[i * 3 + ix_lat])
            a_up.append(pts[i * 3 + ix_up])
        elif z >= hi - span * 0.15:
            b_lat.append(pts[i * 3 + ix_lat])
            b_up.append(pts[i * 3 + ix_up])
    if len(a_lat) < 20 or len(b_lat) < 20:
        return -1
    spread_a = (max(a_lat) - min(a_lat)) + (max(a_up) - min(a_up))
    spread_b = (max(b_lat) - min(b_lat)) + (max(b_up) - min(b_up))
    return -1 if spread_a < spread_b else +1


def dist2(pts, i, x, y, z):
    a = pts[i * 3] - x
    b = pts[i * 3 + 1] - y
    c = pts[i * 3 + 2] - z
    return a * a + b * b + c * c


def place(pts, mn, mx, axes, nose, loc, spread=0.0, avoid=(), minsep=0.06):
    lat, up, lon = axes
    n = len(pts) // 3
    mid = (mn[lat] + mx[lat]) / 2.0
    half = max(mx[lat] - mid, mid - mn[lat]) or 1e-6
    ymin, yr = mn[up], (mx[up] - mn[up]) or 1e-6
    zmin, zr = mn[lon], (mx[lon] - mn[lon]) or 1e-6
    size = math.sqrt(sum((mx[k] - mn[k]) ** 2 for k in range(3)))

    # the hull's own centreline - nine models are not centred on 0
    if loc["side"] == "left":
        side_ok = [i for i in range(n) if pts[i * 3 + lat] < mid - half * 0.02]
    elif loc["side"] == "right":
        side_ok = [i for i in range(n) if pts[i * 3 + lat] > mid + half * 0.02]
    else:
        side_ok = None
    if side_ok is not None and len(side_ok) < 30:
        side_ok = None

    idxs = side_ok if side_ok is not None else range(n)

    p = None
    for attempt in range(9):
        u, v, w = target_uvw(loc, spread + attempt * 0.055 * (1 if attempt % 2 else -1))
        wz = w if nose < 0 else (1.0 - w)
        tx = mid + u * half
        ty = ymin + v * yr
        tz = zmin + wz * zr
        t = [0.0, 0.0, 0.0]
        t[lat], t[up], t[lon] = tx, ty, tz
        bi, bd = -1, None
        for i in idxs:
            d = dist2(pts, i, t[0], t[1], t[2])
            if bd is None or d < bd:
                bd, bi = d, i
        p = [pts[bi * 3], pts[bi * 3 + 1], pts[bi * 3 + 2]]
        if not avoid:
            return p, True
        gap = min(math.sqrt(sum((p[k] - a[k]) ** 2 for k in range(3))) for a in avoid)
        if gap > size * minsep:
            return p, True
    return p, False


def size_of(mn, mx):
    return math.sqrt(sum((mx[k] - mn[k]) ** 2 for k in range(3)))


def push_out(p, mn, mx, frac=0.012):
    c = [(mn[k] + mx[k]) / 2.0 for k in range(3)]
    d = [p[k] - c[k] for k in range(3)]
    nrm = math.sqrt(sum(v * v for v in d))
    if nrm < 1e-9:
        return list(p)
    size = size_of(mn, mx)
    return [p[k] + d[k] / nrm * size * frac for k in range(3)]


def to_unit(p, mn, mx):
    span = max(mx[k] - mn[k] for k in range(3)) or 1.0
    centre = [(mn[k] + mx[k]) / 2.0 for k in range(3)]
    return [round((p[k] - centre[k]) / (span / 2.0), 5) for k in range(3)]


def place_ship(geo, mounts, dim):
    """Every mount on one hull. Returns (hardpoints, frame, crowded) or an error."""
    pts, mn, mx = geo["pts"], geo["min"], geo["max"]
    axes, err, scale = resolve_frame(mn, mx, dim or {})
    if axes is None:
        return None, err, None
    nose = nose_sign(pts, axes[2], axes[0], axes[1])

    bykey = {}
    for mt in mounts:
        loc = read_location(mt["where"], mt["port"])
        bykey.setdefault((loc["side"], loc["vert"], loc["lon"], loc["part"]), []).append((mt, loc))

    hps, placed, crowded = [], [], 0
    for key in sorted(bykey, key=str):
        lst = bykey[key]
        cnt = len(lst)
        for i, (mt, loc) in enumerate(lst):
            sp = 0.0 if cnt == 1 else (i / (cnt - 1.0) - 0.5) * 0.34
            p, ok = place(pts, mn, mx, axes, nose, loc, sp, avoid=placed)
            placed.append(p)
            if not ok:
                crowded += 1
            pcm = push_out(p, mn, mx)
            item = mt.get("item") or {}
            hps.append({
                "where": mt["where"], "port": mt["port"],
                "kind": KIND.get(mt["type"], "other"),
                "pilot": None, "turretOf": None,
                "pos_model": [round(float(c), 3) for c in pcm],
                "unit": to_unit(pcm, mn, mx),
                "read": [k for k in ("side", "vert", "lon", "part") if loc[k]],
                "items": ([{"name": item.get("name"), "type": item.get("type"),
                            "size": item.get("size") or mt.get("size"),
                            "mfr": item.get("mfr"), "port": mt["port"]}]
                          if item.get("name") else []),
            })

    # left/right pairs are mirrored and re-snapped, then separation is
    # re-checked - both carried over from place_fleet.py, where mirroring on its
    # own took overlaps from 15 ships to 28.
    lat_i = axes[0]
    midx = (mn[lat_i] + mx[lat_i]) / 2.0
    groups = {}
    for h in hps:
        w = h["where"].lower()
        if " left" in w or " right" in w:
            k = w.replace(" left", " *").replace(" right", " *")
            groups.setdefault(k, {})[("left" if " left" in w else "right")] = h
    n = len(pts) // 3
    for k in groups:
        pair = groups[k]
        if len(pair) != 2:
            continue
        a, b = pair["left"], pair["right"]
        keep, other = ((a, b) if abs(a["pos_model"][lat_i] - midx)
                       >= abs(b["pos_model"][lat_i] - midx) else (b, a))
        tgt = list(keep["pos_model"])
        tgt[lat_i] = 2 * midx - tgt[lat_i]
        want_left = (other is a)
        if want_left:
            idxs = [i for i in range(n) if pts[i * 3 + lat_i] < midx]
        else:
            idxs = [i for i in range(n) if pts[i * 3 + lat_i] > midx]
        if len(idxs) < 10:
            continue
        bi, bd = -1, None
        for i in idxs:
            d = dist2(pts, i, tgt[0], tgt[1], tgt[2])
            if bd is None or d < bd:
                bd, bi = d, i
        snapped = [pts[bi * 3], pts[bi * 3 + 1], pts[bi * 3 + 2]]
        newp = push_out(snapped, mn, mx)
        other["pos_model"] = [round(float(c), 3) for c in newp]
        other["unit"] = to_unit(newp, mn, mx)

    minsep = size_of(mn, mx) * 0.02
    for i, h in enumerate(hps):
        q = h["pos_model"]
        others = [o["pos_model"] for j, o in enumerate(hps) if j != i]
        if not others:
            break
        if min(math.sqrt(sum((o[k] - q[k]) ** 2 for k in range(3))) for o in others) >= minsep:
            continue
        order = sorted(range(n), key=lambda i2: dist2(pts, i2, q[0], q[1], q[2]))[:4000]
        moved = False
        for idx in order:
            c = [pts[idx * 3], pts[idx * 3 + 1], pts[idx * 3 + 2]]
            if min(math.sqrt(sum((o[k] - c[k]) ** 2 for k in range(3))) for o in others) >= minsep:
                newp = push_out(c, mn, mx)
                h["pos_model"] = [round(float(t), 3) for t in newp]
                h["unit"] = to_unit(newp, mn, mx)
                moved = True
                break
        if not moved:
            crowded += 1

    frame = {"lat": axes[0], "up": axes[1], "len": axes[2],
             "nose_sign": int(nose), "shape_err": round(float(err), 3),
             "model_units_per_metre": round(float(scale), 4)}
    return hps, frame, crowded


# ==========================================================================
# the join
# ==========================================================================

def norm_tokens(s):
    return tokens(s)


def resolve_by_rule(stem, mount_keys, mounts=None):
    """An edition or paint model -> its base hull, BY RULE.

    The base is the LONGEST mount-data key whose words all appear, in order,
    inside the model's name. Longest wins so that Carrack_Expedition_w_C8X
    resolves to "Carrack Expedition" and not to "Carrack".

    Returns (key, why) or (None, why-not). An ambiguous match - two keys of
    equal length - returns None, because a match that could be two ships is not
    a match.
    """
    want = norm_tokens(stem)
    hits = []
    for key in mount_keys:
        kt = norm_tokens(key)
        if not kt:
            continue
        i = 0
        for w in want:
            if i < len(kt) and w == kt[i]:
                i += 1
        if i == len(kt):
            hits.append(key)
    if not hits:
        return None, "no mount-data key's words appear in this model's name"
    longest = max(len(norm_tokens(k)) for k in hits)
    best = sorted(k for k in hits if len(norm_tokens(k)) == longest)
    if len(best) > 1:
        # AN AMBIGUITY ONLY MATTERS IF THE ANSWERS DIFFER.
        #
        # F7C-M_Super_Hornet_Heartseeker_Mk_I matches both "F7C-M Super Hornet
        # Mk I" and "F7C-M Hornet Heartseeker Mk I" - five words each, neither
        # more specific than the other, and no tie-break between them that is
        # not arbitrary. But both carry the SAME ten mounts on the same ports
        # with the same published dimensions, so picking either produces exactly
        # the same page.
        #
        # So the tie is broken by asking whether it is a tie about anything. If
        # the candidates disagree on their mounts it stays a refusal, because
        # then the choice decides what a visitor sees.
        sigs = {json.dumps(mount_signature(mounts.get(k) or {})) for k in best} \
            if mounts else {"?"}
        if len(sigs) == 1 and "?" not in sigs:
            return best[0], ("%d keys match equally well (%s) and they carry "
                             "identical mount data, so the choice changes nothing"
                             % (len(best), ", ".join(best)))
        return None, "ambiguous: %s all match equally well and their mount data " \
                     "differs" % ", ".join(best)
    return best[0], "words of %r appear in order inside %r" % (best[0], stem)


def extents(geo):
    return sorted(geo["max"][k] - geo["min"][k] for k in range(3))


def hull_matches(geo_a, geo_b, tol=0.02):
    """Are these two model files the same hull?

    THIS IS THE CHECK THE PROPORTION GUARD CANNOT DO, and finding that out is
    what this function exists for. `resolve_frame` compares SHAPE and is
    deliberately blind to size, because the model library mixes metres,
    centimetres and normalised units. So it accepts a Gladius hull offered
    Hammerhead dimensions at err 0.11, well inside its 0.35 threshold - measured,
    not supposed. A scale band cannot rescue it either: 19 of the 167 placed
    ships legitimately sit between 0.2 and 0.8 model units per metre, so there is
    no gap to put a threshold in.

    An EDITION, though, is the same mesh with a different skin. Its bounding box
    should be the base hull's box to within rounding. That is a comparison
    between two things we hold, rather than between a model and a number, and it
    is the only one here that can actually tell a Gladius from a Hammerhead.

    Returns (ok, detail).
    """
    a, b = extents(geo_a), extents(geo_b)
    if min(a) <= 0 or min(b) <= 0:
        return False, "degenerate box"
    worst = max(abs(a[i] - b[i]) / max(a[i], b[i]) for i in range(3))
    return worst <= tol, "worst axis differs by %.1f%% (%s vs %s)" % (
        worst * 100,
        [round(v, 2) for v in a], [round(v, 2) for v in b])


def mount_signature(rec):
    """What a mount set IS, for comparing two of them."""
    ms = rec.get("mounts") or []
    return len(ms), sorted((m.get("port") or "") for m in ms)


def main():
    verify_only = "--verify" in sys.argv
    if not GEO or not os.path.isdir(GEO):
        sys.exit("SET CC_GEO_DIR to the folder written by\n"
                 "  node testing/_src/decode_glb_points.js <dir> <models...>\n"
                 "Nothing was written. Without vertices nothing can be placed, and "
                 "an empty result must not be mistaken for 'these ships have no "
                 "hardpoints'.")

    mounts = read_json(MOUNTS, "the extracted mount data")
    fleet = read_json(FLEET, "the hardpoints already placed by place_fleet.py")

    def geo_for(stem):
        p = os.path.join(GEO, stem + ".json")
        if not os.path.exists(p):
            return None
        return read_json(p, "decoded geometry for " + stem)

    # ---- THE PORT IS CHECKED AGAINST THE ORIGINAL -----------------------
    #
    # 100i is already in hardpoints_fleet.json, placed by place_fleet.py in the
    # sandbox. Placing it again here and comparing is what makes this port
    # trustworthy: a port that had drifted would disagree with the file it is
    # meant to match, and would say so here rather than on 29 ships' pages.
    control = geo_for("100i")
    verdict = None
    if control and "100i" in fleet:
        theirs = fleet["100i"]["hardpoints"]
        rec = mounts.get("100i")
        hps, frame, _ = place_ship(control, (rec or {}).get("mounts") or [],
                                   (rec or {}).get("dimension") or {})
        if hps is None:
            verdict = {"ok": False, "why": "the control ship would not place: %s" % frame}
        else:
            by_port = {h["port"]: h for h in hps}
            deltas = []
            for h in theirs:
                mine = by_port.get(h["port"])
                if not mine:
                    continue
                d = math.sqrt(sum((mine["unit"][k] - h["unit"][k]) ** 2 for k in range(3)))
                deltas.append(d)
            worst = max(deltas) if deltas else None
            # 0.10 in unit space is 5% of the hull's longest dimension. The
            # sandbox placed against EVERY vertex and this places against a
            # uniform sample, so the nearest vertex differs slightly and exact
            # equality is not the right test. A frame or nose error would move a
            # marker to the other end of the ship, which is far past this.
            verdict = {"ok": worst is not None and worst <= 0.10,
                       "compared": len(deltas),
                       "worst_unit_delta": round(worst, 4) if worst is not None else None,
                       "frame_matches": frame == fleet["100i"].get("frame")}
        say("port check against place_fleet.py's own output for the 100i:")
        say("  %s" % json.dumps(verdict))
        if not verdict.get("ok"):
            sys.exit("THE PORT DOES NOT REPRODUCE THE ORIGINAL. Nothing was written.\n"
                     "Placing 29 ships with a placement routine that disagrees with "
                     "the one that placed the other 167 would put two different "
                     "answers on one page.")
    else:
        say("port check SKIPPED - no control geometry. Decode 100i.glb to enable it.")
        verdict = {"ok": None, "why": "control geometry not present"}

    if verify_only:
        return 0

    # ---- what is missing ------------------------------------------------
    have_model = sorted(os.path.basename(p)[:-4]
                        for p in [os.path.join(MODELS, f) for f in os.listdir(MODELS)]
                        if p.lower().endswith(".glb"))
    placed_models = {v.get("model", "")[:-4] for v in fleet.values()}
    missing = [m for m in have_model if m not in placed_models]

    out, report = {}, {"placed": [], "refused": [], "skipped": [], "rule": [],
                       "mapped": [], "unchecked_hull": []}

    for stem in missing:
        key, why, how = None, "", ""
        if stem in E1:
            key, why, how = E1[stem], "listed in E1", "mapping"
        else:
            key, why = resolve_by_rule(stem, mounts.keys(), mounts)
            how = "rule"
        if not key:
            report["skipped"].append([stem, why])
            continue
        if key not in mounts:
            report["refused"].append([stem, key, "resolved to a key that does not exist"])
            continue

        rec = mounts[key]

        # THE MOUNT CHECK, where both sides exist.
        own = mounts.get(stem.replace("_", " "))
        if own:
            a, b = mount_signature(own), mount_signature(rec)
            if a != b:
                report["refused"].append([stem, key,
                    "mount data disagrees: %d mounts vs %d" % (a[0], b[0])])
                continue

        geo = geo_for(stem)
        if geo is None:
            report["skipped"].append([stem, "no decoded geometry"])
            continue

        # THE HULL CHECK - the only one that can tell a Gladius from a
        # Hammerhead. Runs where the base hull has a model of its own.
        hull_check = "not performed - the base hull has no model on disk"
        if how == "rule":
            base_model = (fleet.get(key) or {}).get("model") or ""
            base_geo = geo_for(base_model[:-4]) if base_model else None
            if base_geo is not None:
                ok, detail = hull_matches(geo, base_geo)
                if not ok:
                    report["refused"].append([stem, key,
                        "the model is not the same hull as %r: %s" % (key, detail)])
                    continue
                hull_check = "same hull as %r: %s" % (key, detail)
            else:
                report["unchecked_hull"].append([stem, key])

        hps, frame, crowded = place_ship(geo, rec.get("mounts") or [],
                                         rec.get("dimension") or {})
        if hps is None:
            # THE SHAPE CHECK REFUSING IS THE POINT, not a failure of it.
            report["refused"].append([stem, key, frame])
            continue

        out[stem] = {
            "maker": rec.get("maker"),
            "bare": stem,
            "model": stem + ".glb",
            "resolved_from": key,
            "resolved_by": how,
            "why": why,
            "hull_check": hull_check if how == "rule" else
                          "not applicable - this model IS that ship, under a "
                          "shorter file name",
            "dimension": rec.get("dimension"),
            "pilot_dps": rec.get("pilot_dps"),
            "pilot_alpha": rec.get("pilot_alpha"),
            "weapons": rec.get("weapons"),
            "frame": frame,
            "hardpoints": hps,
        }
        report[("mapped" if how == "mapping" else "rule")].append([stem, key, len(hps)])
        report["placed"].append([stem, len(hps), frame["shape_err"], crowded])

    if not os.path.isdir(OUTDIR):
        os.makedirs(OUTDIR)
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(out, fh, separators=(",", ":"), ensure_ascii=False, sort_keys=True)
        fh.write("\n")
    with io.open(REPORT, "w", encoding="utf-8", newline="\n") as fh:
        json.dump(report, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    with io.open(MANIFEST, "w", encoding="utf-8", newline="\n") as fh:
        json.dump({
            "dataset": "holo-hardpoints-join",
            "produced_by": "build_hardpoint_join.py",
            "what_this_is": "Ships whose mount data already existed under a name "
                            "that did not join to the model file. Placed with a "
                            "pure-Python port of place_fleet.py's rules, checked "
                            "against that script's own output for a control ship.",
            "why_a_separate_file": "hardpoints_fleet.json has one writer, "
                                   "place_fleet.py. A second writer on one artifact "
                                   "is a defect this project has paid for three "
                                   "times.",
            "port_check": verdict,
            "counts": {"placed": len(out), "refused": len(report["refused"]),
                       "skipped": len(report["skipped"])},
        }, fh, indent=1, ensure_ascii=False)
        fh.write("\n")

    say("")
    say("wrote %s" % os.path.relpath(OUT, HERE))
    say("  recovered %d ship(s): %d by mapping, %d by rule"
        % (len(out), len(report["mapped"]), len(report["rule"])))
    total = sum(len(v["hardpoints"]) for v in out.values())
    say("  %d hardpoints placed" % total)
    for stem, key, n in sorted(report["mapped"]) + sorted(report["rule"]):
        say("    %-40s <- %-28s %3d mounts" % (stem, key, n))
    if report["refused"]:
        say("  REFUSED (%d) - reported rather than rendered:" % len(report["refused"]))
        for row in report["refused"]:
            say("    %-40s %s" % (row[0], row[2]))
    if report["unchecked_hull"]:
        say("  HULL CHECK NOT PERFORMED for %d pair(s) - the base hull has no "
            "model on disk to compare against. Reported, not counted as passed:"
            % len(report["unchecked_hull"]))
        for stem, key in report["unchecked_hull"]:
            say("    %-40s <- %s" % (stem, key))
    if report["skipped"]:
        say("  no resolution (%d), left as bare hulls:" % len(report["skipped"]))
        for row in report["skipped"][:40]:
            say("    %-40s %s" % (row[0], row[1]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
