# -*- coding: utf-8 -*-
"""PAGES - the one list of what gets copied into testing/_deploy.

WHY THIS IS ITS OWN FILE
========================
There used to be two lists: `PAGES` in build_deploy.py, and
`DEFAULT_ALLOWED_FILES` in check_deploy_clean.py, kept in step BY HAND. The
comment in check_deploy_clean.py named the hazard precisely:

    "Letting the two drift produces a standalone 'unexpected file' failure that
     flatly contradicts a clean build, which is worse than either alone."

It has now happened twice. `download.html` went live while the guard called it
unexpected. Then on 2026-08-22 the ship-page work added four generated files -
cc_viewer.js, loadout_model.gen.js, loadout_marker.gen.js, loadout_eng.gen.js -
and the build reported "safe to deploy" in the same minute the deploy script
REFUSED the same directory.

Rule 14: when a second writer is possible, make it impossible rather than
discouraged. So the list lives here, once, and both sides import it. There is
no longer anything to keep in step.

WHY build_deploy.py CANNOT SIMPLY BE IMPORTED
=============================================
It is a script, not a module - importing it runs the entire build, including
the database gates. So the shared thing has to be the DATA, extracted to
somewhere with no side effects. This file does nothing but declare a list.

Rule 15: no file is opened here, so no encoding is stated. If that ever
changes, state one.
"""

# (source in testing/_src, name written into testing/_deploy)
#
# ADDING A PAGE OR A GENERATED FILE? Add it HERE and nowhere else. The build
# copies from this list and the deploy guard permits from this list, so a file
# that is here is shippable and a file that is not is refused - by the same
# sentence, not by two that agree.
PAGES = [
    # The public download page. Its job is to describe the SmartScreen warning
    # before somebody meets it, because the collector ships unsigned by ruling.
    ('download.src.html', 'download.html'),
    ('keybinds.src.html', 'keybinds.html'),
    ('loadout.src.html',  'loadout.html'),
    ('find.src.html',     'find.html'),
    # FIND's data. H1/H2 of the 2026-08-20 order: the page reads this file
    # instead of calling an API, because a page searching a dated snapshot
    # needs a file and not a server. Generated by build_find_data.py, which
    # the build gate runs before anything here is copied - so a stale copy
    # cannot ship.
    ('find_data.gen.js', 'find_data.gen.js'),
    # Its published sha256 (R7/H5). A file cannot carry its own hash, so this
    # is a second file - generated in the same pass, never typed.
    ('find_checksum.gen.js', 'find_checksum.gen.js'),
    # hardpoint_data.gen.js IS NO LONGER PUBLISHED (N3, 2026-08-22).
    #
    # index.html loaded it with a <script src> to fill its hardpoint panel. That
    # panel is retired - index is a list - and NO PAGE REFERENCES THE FILE ANY
    # MORE. It was 152 KB served to every visitor for nothing.
    #
    # IT IS STILL GENERATED into testing/_src by the build, and
    # checks/_verify_hardpoint_data.py still proves it: it remains the record of
    # what mount data exists, and the alignment gate reads it. What changed is
    # that it is no longer PUBLISHED. Generated and checked is not the same as
    # served, and only the third one had stopped being true.
    #
    # ('hardpoint_data.gen.js', 'hardpoint_data.gen.js'),
    ('kb_modes.gen.js',  'kb_modes.gen.js'),
    # The exporter ships as its own file rather than inlined into the page:
    # inlining would create a second copy of code that already has an owner in
    # testing/_src/sc_export.js, under the order-1 round-trip suite. Rule 14.
    ('sc_export.js',     'sc_export.js'),
    # The action browser's data, generated by build_kb_actions.py. Shipped as
    # its own file for the same reason as sc_export.js: 110 KB of action data
    # pasted into the page would be a second copy of keybinds_site.json.
    ('kb_actions.gen.js', 'kb_actions.gen.js'),
    # The holo viewer. Carries the CC_VENDOR_THREE marker, so the copy loop
    # inlines three.js/DRACO into it - no vendor/ directory in _deploy.
    ('holo.src.html',    'holo.html'),
    ('holo_data.gen.js', 'holo_data.gen.js'),
    ('loadout_data.gen.js', 'loadout_data.gen.js'),
    # THE SHIP VIEWER, ONE COPY (L8). index.html and loadout.html both reach it
    # with <script src>. Shipping it as a file rather than inlining it into
    # each page is the whole point of the extraction: an inlined copy per page
    # IS two copies, and two copies drift.
    ('cc_viewer.js',     'cc_viewer.js'),
    # ClassName -> 3D model for the ship page (L9). Written by the build
    # itself, so it can never be stale relative to CC_MODELS.
    ('loadout_model.gen.js', 'loadout_model.gen.js'),
    # Hull markers (L10). Written by the build from the holo hardpoint
    # placements, bound to PortId so a marker selects one port and no other.
    ('loadout_marker.gen.js', 'loadout_marker.gen.js'),
    # The engineering layer (M2). Loaded ONLY when its tab is opened, which is
    # the whole point of the addendum's per-layer loading - see the ledger for
    # what that actually saves today.
    ('loadout_eng.gen.js', 'loadout_eng.gen.js'),
    # A gamepad diagnostic that shares NO code with the site. That
    # independence is the point: it answers "can this browser see the
    # stick at all" without our own detection logic in the way. Copied
    # verbatim - no vendor marker, no styling, no nav.
    ('stick-test.src.html', 'stick-test.html'),
]

# index.html is assembled rather than copied, so it is not in PAGES - but it is
# the one file the site cannot be without, and the guard must permit it.
ASSEMBLED = {'index.html'}

# Everything permitted at the top level of testing/_deploy, derived.
ALLOWED_FILES = ASSEMBLED | {out for _src, out in PAGES}
