/* GENERATED by build_find_data.py - do not hand edit.

   R7/H5. The sha256 of find_data.gen.js, published beside it so a visitor can
   check every number on the page against the file the page actually read.

   This is a separate file for one unavoidable reason: a file cannot contain
   its own sha256. It is generated in the same pass as the data, from the same
   bytes, so the two cannot disagree - and build_find_data.py --check refuses
   a checksum that describes a previous version of the data. A correct data
   file beside a stale checksum is worse than no checksum: it tells a visitor
   the file was tampered with when it was not.

   To check it yourself, after downloading the file:
     Windows   certutil -hashfile find_data.gen.js SHA256
     Linux/mac sha256sum find_data.gen.js
*/
const FIND_CHECKSUM={"algorithm":"sha256","bytes":993157,"file":"find_data.gen.js","sha256":"dce035da5b436b6180833ff0b127ae27485d101366c49eab4edefc9045040f5f"};
