"""add ship items component schema (weapons, missiles, missile racks, gimbal mounts, turrets)

Revision ID: 219446ebce6a
Revises: 4d271b0f0eae
Create Date: 2026-07-30 07:38:35.814480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '219446ebce6a'
down_revision: Union[str, Sequence[str], None] = '4d271b0f0eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('components',
    sa.Column('component_type_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('class_name', sa.String(length=150), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_components_confidence_valid'),
    sa.ForeignKeyConstraint(['component_type_id'], ['component_types.id'], ),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name', name='uq_components_class_name')
    )
    op.create_index(op.f('ix_components_component_type_id'), 'components', ['component_type_id'], unique=False)
    op.create_index(op.f('ix_components_manufacturer_id'), 'components', ['manufacturer_id'], unique=False)
    op.create_table('gimbal_mount_details',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('accepts_weapon_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('missile_details',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('guidance_type', sa.String(length=30), nullable=True),
    sa.Column('tracking_range_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lock_time_s', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('speed_mps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('missile_rack_details',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('native_missile_size', sa.Integer(), nullable=True),
    sa.Column('missile_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('turret_details',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('weapon_slots', sa.Integer(), nullable=True),
    sa.Column('slot_weapon_size', sa.Integer(), nullable=True),
    sa.Column('manned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id')
    )
    op.create_table('weapon_details',
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(length=30), nullable=True),
    sa.Column('fire_mode', sa.String(length=30), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('damage_per_shot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ammo_capacity', sa.Integer(), nullable=True),
    sa.Column('velocity_mps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('range_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('component_id')
    )
    # ### end Alembic commands ###

    # --- Manually added: seed the component_types lookup table (not part of
    # autogenerate - this is app-owned taxonomy data, not a schema change).
    # Per ARCHITECTURE_DECISIONS.md section 1: adding a new category later
    # (shields, coolers, power plants, quantum drives) is a data insert here,
    # not a migration. These 5 are the categories this migration's typed
    # detail tables actually support - keep this list and the *_details
    # tables in sync if either changes.
    component_types = sa.table(
        "component_types",
        sa.column("key", sa.String),
        sa.column("label", sa.String),
    )
    op.bulk_insert(component_types, [
        {"key": "weapon", "label": "Weapon"},
        {"key": "missile", "label": "Missile"},
        {"key": "missile_rack", "label": "Missile Rack"},
        {"key": "gimbal_mount", "label": "Gimbal Mount"},
        {"key": "turret", "label": "Turret"},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon_details')
    op.drop_table('turret_details')
    op.drop_table('missile_rack_details')
    op.drop_table('missile_details')
    op.drop_table('gimbal_mount_details')
    op.drop_index(op.f('ix_components_manufacturer_id'), table_name='components')
    op.drop_index(op.f('ix_components_component_type_id'), table_name='components')
    op.drop_table('components')
    op.drop_table('component_types')
    # ### end Alembic commands ###
