"""B6 shop items source kind for commodities

WHY THE UNIQUE KEY IS BEING WIDENED, measured rather than anticipated:
UEX numbers commodities from 1 in an id space entirely separate from items,
and 200 of the 204 commodity ids COLLIDE with item ids while meaning
something completely different - id 1 is the "Omnisky III Cannon" as an item
and "Agricium" as a commodity. Under uq_shop_items_uex_id the second of each
pair would have been refused outright, or upserted over the first.

This is a WIDENING, not a relaxation: every row valid under the old
constraint is still valid, because all 7,728 existing rows take the
server_default of 'item'. Nothing existing can become non-unique.

The dropped constraint is replaced in the same migration, so there is no
window in which shop_items is unconstrained.

Revision ID: 250bdcd72ac3
Revises: 2b99ac053efa
Create Date: 2026-08-19 14:22:00.515851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250bdcd72ac3'
down_revision: Union[str, Sequence[str], None] = '2b99ac053efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_items', sa.Column('source_kind', sa.String(length=20), server_default='item', nullable=False))
    op.drop_constraint(op.f('uq_shop_items_uex_id'), 'shop_items', type_='unique')
    op.create_index(op.f('ix_shop_items_source_kind'), 'shop_items', ['source_kind'], unique=False)
    op.create_unique_constraint('uq_shop_items_source_kind_uex_id', 'shop_items', ['source_kind', 'uex_id'])
    # ### end Alembic commands ###

    # Added by hand: alembic does not autogenerate CHECK constraints, so a
    # constraint declared in the model would silently never reach the
    # database. That is its own small silent-success trap - the model would
    # claim an invariant nothing enforces.
    op.create_check_constraint(
        "ck_shop_items_source_kind_valid", "shop_items",
        "source_kind IN ('item', 'commodity')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shop_items_source_kind_uex_id', 'shop_items', type_='unique')
    op.drop_index(op.f('ix_shop_items_source_kind'), table_name='shop_items')
    op.create_unique_constraint(op.f('uq_shop_items_uex_id'), 'shop_items', ['uex_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('shop_items', 'source_kind')
    # ### end Alembic commands ###
