"""A5 item prices

Revision ID: 2b99ac053efa
Revises: ca347e657da7
Create Date: 2026-08-19 14:04:56.147164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b99ac053efa'
down_revision: Union[str, Sequence[str], None] = 'ca347e657da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_item_id', sa.Integer(), nullable=False),
    sa.Column('terminal_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('price_buy', sa.Integer(), nullable=True),
    sa.Column('price_sell', sa.Integer(), nullable=True),
    sa.Column('uex_price_id', sa.Integer(), nullable=True),
    sa.Column('source_date_modified', sa.DateTime(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_buy IS NOT NULL OR price_sell IS NOT NULL', name='ck_item_prices_has_at_least_one_side'),
    sa.CheckConstraint('price_buy IS NULL OR price_buy >= 0', name='ck_item_prices_price_buy_non_negative'),
    sa.CheckConstraint('price_sell IS NULL OR price_sell >= 0', name='ck_item_prices_price_sell_non_negative'),
    sa.ForeignKeyConstraint(['shop_item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_item_id', 'terminal_id', 'snapshot_id', name='uq_item_prices_item_terminal_snapshot')
    )
    op.create_index('ix_item_prices_price_buy', 'item_prices', ['price_buy'], unique=False)
    op.create_index('ix_item_prices_price_sell', 'item_prices', ['price_sell'], unique=False)
    op.create_index(op.f('ix_item_prices_shop_item_id'), 'item_prices', ['shop_item_id'], unique=False)
    op.create_index(op.f('ix_item_prices_snapshot_id'), 'item_prices', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_item_prices_source_date_modified'), 'item_prices', ['source_date_modified'], unique=False)
    op.create_index(op.f('ix_item_prices_terminal_id'), 'item_prices', ['terminal_id'], unique=False)
    op.create_index(op.f('ix_item_prices_uex_price_id'), 'item_prices', ['uex_price_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_prices_uex_price_id'), table_name='item_prices')
    op.drop_index(op.f('ix_item_prices_terminal_id'), table_name='item_prices')
    op.drop_index(op.f('ix_item_prices_source_date_modified'), table_name='item_prices')
    op.drop_index(op.f('ix_item_prices_snapshot_id'), table_name='item_prices')
    op.drop_index(op.f('ix_item_prices_shop_item_id'), table_name='item_prices')
    op.drop_index('ix_item_prices_price_sell', table_name='item_prices')
    op.drop_index('ix_item_prices_price_buy', table_name='item_prices')
    op.drop_table('item_prices')
    # ### end Alembic commands ###
