"""G8 ship hardpoint slots and coverage

Revision ID: 71d65b7b4026
Revises: d3115d32c70d
Create Date: 2026-08-19 22:39:32.691569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71d65b7b4026'
down_revision: Union[str, Sequence[str], None] = 'd3115d32c70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship_hardpoint_coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('slot_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_dataset', sa.String(length=50), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("(status = 'placed' AND slot_count > 0) OR (status <> 'placed' AND slot_count = 0)", name='ck_ship_hardpoint_coverage_count_matches_status'),
    sa.CheckConstraint("status IN ('placed', 'refused', 'skipped', 'absent')", name='ck_ship_hardpoint_coverage_status_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key', name='uq_ship_hardpoint_coverage_model')
    )
    op.create_index(op.f('ix_ship_hardpoint_coverage_model_key'), 'ship_hardpoint_coverage', ['model_key'], unique=False)
    op.create_index(op.f('ix_ship_hardpoint_coverage_source_dataset'), 'ship_hardpoint_coverage', ['source_dataset'], unique=False)
    op.create_index(op.f('ix_ship_hardpoint_coverage_status'), 'ship_hardpoint_coverage', ['status'], unique=False)
    op.create_table('ship_hardpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=150), nullable=False),
    sa.Column('port', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('stock_item_name', sa.String(length=255), nullable=True),
    sa.Column('stock_item_type', sa.String(length=100), nullable=True),
    sa.Column('source_dataset', sa.String(length=50), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key', 'port', name='uq_ship_hardpoints_model_port')
    )
    op.create_index(op.f('ix_ship_hardpoints_kind'), 'ship_hardpoints', ['kind'], unique=False)
    op.create_index(op.f('ix_ship_hardpoints_model_key'), 'ship_hardpoints', ['model_key'], unique=False)
    op.create_index('ix_ship_hardpoints_model_kind', 'ship_hardpoints', ['model_key', 'kind'], unique=False)
    op.create_index(op.f('ix_ship_hardpoints_size'), 'ship_hardpoints', ['size'], unique=False)
    op.create_index(op.f('ix_ship_hardpoints_source_dataset'), 'ship_hardpoints', ['source_dataset'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ship_hardpoints_source_dataset'), table_name='ship_hardpoints')
    op.drop_index(op.f('ix_ship_hardpoints_size'), table_name='ship_hardpoints')
    op.drop_index('ix_ship_hardpoints_model_kind', table_name='ship_hardpoints')
    op.drop_index(op.f('ix_ship_hardpoints_model_key'), table_name='ship_hardpoints')
    op.drop_index(op.f('ix_ship_hardpoints_kind'), table_name='ship_hardpoints')
    op.drop_table('ship_hardpoints')
    op.drop_index(op.f('ix_ship_hardpoint_coverage_status'), table_name='ship_hardpoint_coverage')
    op.drop_index(op.f('ix_ship_hardpoint_coverage_source_dataset'), table_name='ship_hardpoint_coverage')
    op.drop_index(op.f('ix_ship_hardpoint_coverage_model_key'), table_name='ship_hardpoint_coverage')
    op.drop_table('ship_hardpoint_coverage')
    # ### end Alembic commands ###
