"""lifecycle columns: mark absence instead of leaving a lie

Revision ID: 7917a851cc5d
Revises: a1c9d4e77b02
Create Date: 2026-08-08 17:34:29.854684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7917a851cc5d'
down_revision: Union[str, Sequence[str], None] = 'a1c9d4e77b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ships', sa.Column('successor_id', sa.Integer(), nullable=True))
    op.add_column('ships', sa.Column('first_seen_patch', sa.String(length=50), nullable=True))
    op.add_column('ships', sa.Column('last_seen_patch', sa.String(length=50), nullable=True))
    op.add_column('ships', sa.Column('lifecycle_status', sa.String(length=20), server_default='live', nullable=False))
    op.add_column('ships', sa.Column('evidence_tier', sa.String(length=20), server_default='sealed', nullable=False))
    op.add_column('ships', sa.Column('removal_note', sa.Text(), nullable=True))
    op.create_index(op.f('ix_ships_evidence_tier'), 'ships', ['evidence_tier'], unique=False)
    op.create_index(op.f('ix_ships_lifecycle_status'), 'ships', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_ships_successor_id'), 'ships', ['successor_id'], unique=False)
    op.create_foreign_key(
        'fk_ships_successor_id', 'ships', 'ships', ['successor_id'], ['id'])
    # ### end Alembic commands ###

    # ---- added by hand: alembic autogenerate does NOT emit CheckConstraints --
    # Without these the columns accept any string. The deletion audit found
    # exactly that shape elsewhere - "silently accepting a value nothing
    # understands" - and an unconstrained lifecycle_status is worse than none,
    # because a typo reads as a valid state on the page.
    op.create_check_constraint(
        'ck_ships_lifecycle_status_valid', 'ships',
        "lifecycle_status IN ('live','retired','renamed','replaced',"
        "'never_released','unknown')")
    op.create_check_constraint(
        'ck_ships_evidence_tier_valid', 'ships',
        "evidence_tier IN ('sealed','external','testimony')")

    # ships.status (purchasable / pledge_only) and its CHECK are deliberately
    # UNTOUCHED. It answers commercial availability; lifecycle_status answers
    # existence. A ship can be pledge_only AND retired.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_ships_evidence_tier_valid', 'ships', type_='check')
    op.drop_constraint('ck_ships_lifecycle_status_valid', 'ships', type_='check')
    op.drop_constraint('fk_ships_successor_id', 'ships', type_='foreignkey')
    op.drop_index(op.f('ix_ships_successor_id'), table_name='ships')
    op.drop_index(op.f('ix_ships_lifecycle_status'), table_name='ships')
    op.drop_index(op.f('ix_ships_evidence_tier'), table_name='ships')
    op.drop_column('ships', 'removal_note')
    op.drop_column('ships', 'evidence_tier')
    op.drop_column('ships', 'lifecycle_status')
    op.drop_column('ships', 'last_seen_patch')
    op.drop_column('ships', 'first_seen_patch')
    op.drop_column('ships', 'successor_id')
    # ### end Alembic commands ###
