"""add ships.status

Revision ID: 8f37bb885052
Revises: f6140ac5f018
Create Date: 2026-07-24 14:25:55.669915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f37bb885052'
down_revision: Union[str, Sequence[str], None] = 'f6140ac5f018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ships', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'status')
    # ### end Alembic commands ###
