"""A1 location hierarchy for the shop and price layer

Revision ID: 9df170bd1cf2
Revises: 7917a851cc5d
Create Date: 2026-08-19 13:49:25.407434

Item A1 of docs/ORDER_shop-and-price-layer-RUN-CONTINUOUSLY-2026-08-19.md.

Creates `locations`: one self-referential table holding every level of the
Star Citizen place hierarchy that UEX names (star system, planet, moon, space
station, outpost, city). See app/models.py:Location for why this is one table
and not eight, and app/locations.py for the resolver that turns a row into a
readable string.

REVIEWED FOR DESTRUCTIVE OPERATIONS BEFORE APPLYING. Autogenerate on this repo
has previously proposed dropping ship_registry and the three pipeline_* tables
(see alembic/env.py), so its output is read rather than trusted. `upgrade()`
here is purely additive - one CREATE TABLE and four CREATE INDEX, nothing else.
The only drops are in `downgrade()`, and only of the table this revision
created.

`kind` + `uex_id` is the unique key, NOT uex_id alone: UEX numbers each
endpoint from 1, so star_system 1 and planet 1 are different places, and
anything joining on uex_id without also matching kind is a bug.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9df170bd1cf2'
down_revision: Union[str, Sequence[str], None] = '7917a851cc5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('uex_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=200), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('star_system_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('resolved_path', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_locations_confidence_valid'),
    sa.CheckConstraint("kind IN ('star_system', 'planet', 'orbit', 'moon', 'space_station', 'outpost', 'poi', 'city')", name='ck_locations_kind_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['star_system_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'uex_id', name='uq_locations_kind_uex_id')
    )
    op.create_index(op.f('ix_locations_kind'), 'locations', ['kind'], unique=False)
    op.create_index(op.f('ix_locations_parent_id'), 'locations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_locations_planet_id'), 'locations', ['planet_id'], unique=False)
    op.create_index(op.f('ix_locations_star_system_id'), 'locations', ['star_system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_star_system_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_planet_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_parent_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_kind'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
