"""initial schema

Revision ID: c40fb8295161
Revises: 
Create Date: 2026-07-24 13:51:02.130121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40fb8295161'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patches',
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('released_on', sa.Date(), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_patches_confidence_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('manufacturers',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_manufacturers_confidence_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('systems',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_systems_confidence_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dealers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_dealers_confidence_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ships',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_ships_confidence_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pledge_links',
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('warbond', sa.Boolean(), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_pledge_links_confidence_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ship_dealer_listings',
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('in_game_price_auec', sa.Integer(), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_ship_dealer_listings_confidence_valid'),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_id', 'dealer_id', name='uq_ship_dealer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship_dealer_listings')
    op.drop_table('pledge_links')
    op.drop_table('ships')
    op.drop_table('dealers')
    op.drop_table('systems')
    op.drop_table('manufacturers')
    op.drop_table('patches')
    # ### end Alembic commands ###
