"""A4 shop items

Revision ID: c5f93160bd87
Revises: e6b3d0ad40b4
Create Date: 2026-08-19 14:00:54.395470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5f93160bd87'
down_revision: Union[str, Sequence[str], None] = 'e6b3d0ad40b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_items',
    sa.Column('uex_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=150), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('vehicle_name', sa.String(length=255), nullable=True),
    sa.Column('size', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('url_store', sa.Text(), nullable=True),
    sa.Column('source_date_modified', sa.DateTime(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_shop_items_confidence_valid'),
    sa.ForeignKeyConstraint(['category_id'], ['item_categories.id'], ),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uex_id', name='uq_shop_items_uex_id')
    )
    op.create_index(op.f('ix_shop_items_category_id'), 'shop_items', ['category_id'], unique=False)
    op.create_index('ix_shop_items_name_trgm', 'shop_items', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_shop_items_section'), 'shop_items', ['section'], unique=False)
    op.create_index(op.f('ix_shop_items_slug'), 'shop_items', ['slug'], unique=False)
    op.create_index(op.f('ix_shop_items_source_date_modified'), 'shop_items', ['source_date_modified'], unique=False)
    op.create_index(op.f('ix_shop_items_uuid'), 'shop_items', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_items_uuid'), table_name='shop_items')
    op.drop_index(op.f('ix_shop_items_source_date_modified'), table_name='shop_items')
    op.drop_index(op.f('ix_shop_items_slug'), table_name='shop_items')
    op.drop_index(op.f('ix_shop_items_section'), table_name='shop_items')
    op.drop_index('ix_shop_items_name_trgm', table_name='shop_items', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_shop_items_category_id'), table_name='shop_items')
    op.drop_table('shop_items')
    # ### end Alembic commands ###
