"""A6 snapshots

Revision ID: ca347e657da7
Revises: c5f93160bd87
Create Date: 2026-08-19 14:02:26.150672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca347e657da7'
down_revision: Union[str, Sequence[str], None] = 'c5f93160bd87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('snapshot_key', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('row_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'snapshot_key', name='uq_snapshots_source_key')
    )
    op.create_index(op.f('ix_snapshots_captured_at'), 'snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_snapshots_source'), 'snapshots', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_source'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_captured_at'), table_name='snapshots')
    op.drop_table('snapshots')
    # ### end Alembic commands ###
