"""G5 shop item commodity cross reference

R1: UEX describes the same tradeable substance twice - as an item in category
36 (158 rows, none priced) and as a commodity (204 rows, 147 priced). The site
shows the commodity side. BOTH STAY STORED, per the standing preservation rule,
and this table records where the two describe the same thing.

A LINK, NOT A MERGE, AND NOT A TOMBSTONE. Merging would destroy the evidence
that the two representations differ - the item side says "Aslarite (Raw)" and
the commodity side says "Aslarite (Ore)" - which is the one thing this pair is
informative about. Neither shop_items row is touched by this migration.

Additive only: one new table, no column added to an existing one, nothing
dropped. Reverses by dropping the table.

Revision ID: d3115d32c70d
Revises: 250bdcd72ac3
Create Date: 2026-08-19 22:05:50.473424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3115d32c70d'
down_revision: Union[str, Sequence[str], None] = '250bdcd72ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_item_commodity_xref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_shop_item_id', sa.Integer(), nullable=False),
    sa.Column('commodity_shop_item_id', sa.Integer(), nullable=False),
    sa.Column('match_method', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_method IN ('exact_name', 'token_set')", name='ck_shop_item_commodity_xref_method_valid'),
    sa.CheckConstraint('item_shop_item_id <> commodity_shop_item_id', name='ck_shop_item_commodity_xref_distinct'),
    sa.ForeignKeyConstraint(['commodity_shop_item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['item_shop_item_id'], ['shop_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity_shop_item_id', name='uq_shop_item_commodity_xref_commodity'),
    sa.UniqueConstraint('item_shop_item_id', name='uq_shop_item_commodity_xref_item')
    )
    op.create_index(op.f('ix_shop_item_commodity_xref_commodity_shop_item_id'), 'shop_item_commodity_xref', ['commodity_shop_item_id'], unique=False)
    op.create_index(op.f('ix_shop_item_commodity_xref_item_shop_item_id'), 'shop_item_commodity_xref', ['item_shop_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_item_commodity_xref_item_shop_item_id'), table_name='shop_item_commodity_xref')
    op.drop_index(op.f('ix_shop_item_commodity_xref_commodity_shop_item_id'), table_name='shop_item_commodity_xref')
    op.drop_table('shop_item_commodity_xref')
    # ### end Alembic commands ###
