"""A3 item categories

Revision ID: e6b3d0ad40b4
Revises: fb37274717f7
Create Date: 2026-08-19 13:56:13.237630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6b3d0ad40b4'
down_revision: Union[str, Sequence[str], None] = 'fb37274717f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_categories',
    sa.Column('uex_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_game_related', sa.Boolean(), nullable=True),
    sa.Column('is_mining', sa.Boolean(), nullable=True),
    sa.Column('source_date_modified', sa.DateTime(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_item_categories_confidence_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uex_id', name='uq_item_categories_uex_id')
    )
    op.create_index(op.f('ix_item_categories_is_game_related'), 'item_categories', ['is_game_related'], unique=False)
    op.create_index(op.f('ix_item_categories_is_mining'), 'item_categories', ['is_mining'], unique=False)
    op.create_index(op.f('ix_item_categories_section'), 'item_categories', ['section'], unique=False)
    op.create_index(op.f('ix_item_categories_type'), 'item_categories', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_categories_type'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_section'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_is_mining'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_is_game_related'), table_name='item_categories')
    op.drop_table('item_categories')
    # ### end Alembic commands ###
