"""A2 terminals

Revision ID: fb37274717f7
Revises: 9df170bd1cf2
Create Date: 2026-08-19 13:54:21.637115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb37274717f7'
down_revision: Union[str, Sequence[str], None] = '9df170bd1cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terminals',
    sa.Column('uex_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('displayname', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('star_system_id', sa.Integer(), nullable=True),
    sa.Column('resolved_path', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_available_live', sa.Boolean(), nullable=True),
    sa.Column('source_date_modified', sa.DateTime(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_verified_patch', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_source', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.String(length=20), server_default='unverified', nullable=False),
    sa.CheckConstraint("confidence IN ('unverified', 'low', 'medium', 'high', 'verified')", name='ck_terminals_confidence_valid'),
    sa.ForeignKeyConstraint(['last_verified_patch'], ['patches.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['star_system_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uex_id', name='uq_terminals_uex_id')
    )
    op.create_index(op.f('ix_terminals_is_available'), 'terminals', ['is_available'], unique=False)
    op.create_index(op.f('ix_terminals_location_id'), 'terminals', ['location_id'], unique=False)
    op.create_index('ix_terminals_name_trgm', 'terminals', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_terminals_source_date_modified'), 'terminals', ['source_date_modified'], unique=False)
    op.create_index(op.f('ix_terminals_star_system_id'), 'terminals', ['star_system_id'], unique=False)
    op.create_index(op.f('ix_terminals_type'), 'terminals', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terminals_type'), table_name='terminals')
    op.drop_index(op.f('ix_terminals_star_system_id'), table_name='terminals')
    op.drop_index(op.f('ix_terminals_source_date_modified'), table_name='terminals')
    op.drop_index('ix_terminals_name_trgm', table_name='terminals', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_terminals_location_id'), table_name='terminals')
    op.drop_index(op.f('ix_terminals_is_available'), table_name='terminals')
    op.drop_table('terminals')
    # ### end Alembic commands ###
