# deploy-receiver.ps1 - stand up the thing that receives exports.
#
#     powershell -ExecutionPolicy Bypass -File .\deploy-receiver.ps1
#     powershell -ExecutionPolicy Bypass -File .\deploy-receiver.ps1 -Deploy
#
# Without -Deploy it changes nothing and prints exactly what it would do.
#
# ---------------------------------------------------------------------------
# WHY THIS IS THE LAST PIECE
# ---------------------------------------------------------------------------
#
# Right now `send_url` is blank on every machine, so SEND MY DATA packages a zip
# to that person's own disk and stops. The data comes back by hand, over Discord,
# for every person, after every session, forever. That is not a lighter version
# of the design; it is the absence of it, and it is the part that quietly stops
# happening after week two.
#
# With this deployed, one click packages, uploads, gets a byte-for-byte
# confirmation, and only then clears what was sent. Nobody has to remember
# anything and you never touch their machine again.
#
# ---------------------------------------------------------------------------
# WHAT IT COSTS: NOTHING, AND THAT IS A REQUIREMENT NOT A PREFERENCE
# ---------------------------------------------------------------------------
#
# Standing rule: "No API, no paid service, no running cost. Ever."
#
# Cloudflare Workers free tier is 100,000 requests/day. R2 free tier is 10 GB
# stored, 1 million writes/month, and - the part that matters for a project that
# will eventually serve ship models - NO EGRESS CHARGE. A handful of contributors
# uploading a few MB a day is not close to any of those edges.
#
# ---------------------------------------------------------------------------
# THE KEY IS NOT A PASSWORD, AND PRETENDING OTHERWISE WOULD BE WORSE
# ---------------------------------------------------------------------------
#
# It ships inside a settings file on machines other people own. It is
# extractable, and it must be assumed public eventually.
#
# What it buys is a closed door instead of an open one: it stops drive-by abuse
# of a public endpoint. It is not authentication. That is exactly why the
# receiver has NO route that lists, reads, or deletes - not even with the key in
# hand. A leaked add-only key costs junk in a bucket. A leaked read key would
# cost every contributor's data.

param(
    [switch] $Deploy,
    [string] $WorkerName = "collector-receiver",
    [string] $BucketName = "collector-uploads"
)

$ErrorActionPreference = "Stop"
$here = Split-Path -Parent $MyInvocation.MyCommand.Definition

function Fail($m) { Write-Host ""; Write-Host "REFUSED: $m" -ForegroundColor Red; exit 1 }
function Step($m) { Write-Host ""; Write-Host "== $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "   ok   $m" -ForegroundColor Green }
function Note($m) { Write-Host "        $m" -ForegroundColor DarkGray }

Step "checking what is here"
$worker = Join-Path $here "collector-receiver.worker.js"
if (-not (Test-Path $worker)) { Fail "collector-receiver.worker.js is not in this folder." }
Ok "collector-receiver.worker.js found"

$wrangler = Get-Command wrangler -ErrorAction SilentlyContinue
if (-not $wrangler) {
    Write-Host ""
    Write-Host "The Cloudflare CLI (wrangler) is not installed." -ForegroundColor Yellow
    Write-Host "    npm install -g wrangler"
    Write-Host "    wrangler login"
    Write-Host "Then run this again."
    exit 1
}
Ok "wrangler is installed"

# ---------------------------------------------------------------------------
# THE KEY. Generated here, from a real random source, and shown once.
# ---------------------------------------------------------------------------
Step "the upload key"
$keyFile = Join-Path $here "collector-upload-key.txt"
if (Test-Path $keyFile) {
    $uploadKey = (Get-Content $keyFile -Raw).Trim()
    Ok "reusing the key already in collector-upload-key.txt"
    Note "delete that file to roll the key - but every collector already out there"
    Note "carries the old one and would stop being able to send."
} else {
    # RNGCryptoServiceProvider, not Get-Random. Get-Random is seeded from the
    # clock and is documented as unsuitable for anything security-related; a key
    # that can be regenerated by knowing roughly when it was made is not a key.
    $bytes = New-Object byte[] 32
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $uploadKey = -join ($bytes | ForEach-Object { $_.ToString("x2") })
    if (-not $Deploy) {
        Note "would generate a new 64-character key (not written during a dry run)"
    } else {
        Set-Content -LiteralPath $keyFile -Value $uploadKey -Encoding ASCII
        Ok "generated a new key and saved it to collector-upload-key.txt"
        Note "THIS FILE IS NOT IN THE PACKAGE and must never be committed - check .gitignore"
    }
}

# ---------------------------------------------------------------------------
# THE CONFIG
# ---------------------------------------------------------------------------
Step "writing wrangler.toml"
$toml = @"
name = "$WorkerName"
main = "collector-receiver.worker.js"
compatibility_date = "2026-08-01"

# The bucket the Worker writes into. The binding name BUCKET is what the
# Worker's code refers to - renaming it here breaks env.BUCKET.put silently at
# runtime rather than at deploy, so leave it alone.
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "$BucketName"
"@
if ($Deploy) {
    Set-Content -LiteralPath (Join-Path $here "wrangler.toml") -Value $toml -Encoding UTF8
    Ok "wrote wrangler.toml"
} else {
    Note "would write wrangler.toml binding BUCKET -> $BucketName"
}

if (-not $Deploy) {
    Write-Host ""
    Write-Host "Dry run. Nothing was created, deployed, or written." -ForegroundColor Yellow
    Write-Host "It would:"
    Write-Host "    1. create R2 bucket '$BucketName'"
    Write-Host "    2. deploy worker '$WorkerName'"
    Write-Host "    3. set the UPLOAD_KEY secret"
    Write-Host "    4. upload a test zip and verify the hash round-trips"
    Write-Host "    5. prove a wrong key and a non-zip are both REFUSED"
    Write-Host "    6. print the two lines to put in collector-settings.txt"
    Write-Host ""
    Write-Host "Re-run with -Deploy when you are ready."
    exit 0
}

# ---------------------------------------------------------------------------
# BUCKET, WORKER, SECRET
# ---------------------------------------------------------------------------
Step "creating the bucket"
& wrangler r2 bucket create $BucketName 2>&1 | ForEach-Object { Note $_ }
Note "an 'already exists' here is fine and expected on a re-run"

Step "deploying the worker"
Push-Location $here
try {
    & wrangler deploy 2>&1 | ForEach-Object { Note $_ }
    if ($LASTEXITCODE -ne 0) { Fail "wrangler deploy failed. Nothing is receiving yet." }

    Step "setting the upload key"
    # Piped, so the key never appears in a command line - command lines are
    # visible to other processes and land in shell history.
    $uploadKey | & wrangler secret put UPLOAD_KEY 2>&1 | ForEach-Object { Note $_ }
    if ($LASTEXITCODE -ne 0) { Fail "could not set UPLOAD_KEY. The worker is deployed but will refuse everything." }
    Ok "UPLOAD_KEY set"
} finally {
    Pop-Location
}

# ---------------------------------------------------------------------------
# WHERE IS IT?
# ---------------------------------------------------------------------------
Step "finding the worker's address"
$sub = ""
$deployOut = & wrangler deployments list 2>&1 | Out-String
if ($deployOut -match "https://([a-z0-9\-]+\.[a-z0-9\-]+\.workers\.dev)") {
    $sendUrl = "https://$($Matches[1])"
} else {
    Write-Host ""
    Write-Host "Could not read the worker URL automatically." -ForegroundColor Yellow
    Write-Host "It is printed in the deploy output above and looks like:"
    Write-Host "    https://$WorkerName.<your-subdomain>.workers.dev"
    $sendUrl = Read-Host "Paste it here"
}
$sendUrl = $sendUrl.TrimEnd("/")
Ok "send_url = $sendUrl"

# ---------------------------------------------------------------------------
# THE VERIFICATION. Every check below has a case that can fail it - hard rule 12.
# ---------------------------------------------------------------------------
Step "proving it actually works, and actually refuses"

# A real, minimal zip. Built rather than faked, because the receiver checks the
# PK header and a fake would be rejected for the wrong reason.
$tmp = Join-Path $env:TEMP "cc-receiver-probe"
if (Test-Path $tmp) { Remove-Item $tmp -Recurse -Force }
New-Item -ItemType Directory -Path $tmp | Out-Null
Set-Content -LiteralPath (Join-Path $tmp "hello.txt") -Value "receiver probe" -Encoding ASCII
$probeZip = Join-Path $env:TEMP "cc-receiver-probe.zip"
if (Test-Path $probeZip) { Remove-Item $probeZip -Force }
Compress-Archive -Path (Join-Path $tmp "*") -DestinationPath $probeZip
$probeBytes = [IO.File]::ReadAllBytes($probeZip)
$probeSha = (Get-FileHash -Algorithm SHA256 -LiteralPath $probeZip).Hash.ToLower()
Note "probe zip is $($probeBytes.Length) bytes, sha256 $($probeSha.Substring(0,16))..."

function Post($bytes, $key, $sha) {
    $h = @{ "X-Collector-Install" = "deploy-probe"; "X-Collector-Version" = "probe" }
    if ($key) { $h["X-Collector-Key"] = $key }
    if ($sha) { $h["X-Collector-Sha256"] = $sha }
    try {
        $r = Invoke-WebRequest -Uri $sendUrl -Method POST -Body $bytes `
             -ContentType "application/zip" -Headers $h -TimeoutSec 60 -UseBasicParsing
        return @{ code = $r.StatusCode; body = ($r.Content | ConvertFrom-Json) }
    } catch {
        $code = 0
        if ($_.Exception.Response) { $code = [int]$_.Exception.Response.StatusCode }
        return @{ code = $code; body = $null }
    }
}

# 1. THE POSITIVE. A real upload with the right key must be accepted, and the
#    hash it returns must be the one WE computed - not the one we told it.
$r1 = Post $probeBytes $uploadKey $probeSha
if ($r1.code -eq 200 -and $r1.body.ok -and $r1.body.sha256 -eq $probeSha) {
    Ok "a real upload is accepted and the receiver's OWN hash matches ours"
    Note "stored as $($r1.body.stored_as)"
} else {
    Fail "the upload did not succeed (HTTP $($r1.code)). Nothing is safe to point collectors at yet."
}

# 2. NEGATIVE CONTROL - the wrong key must be REFUSED. Without this, check 1
#    would also pass on a worker that accepted anything from anyone.
$r2 = Post $probeBytes "not-the-key" $probeSha
if ($r2.code -eq 403) {
    Ok "a wrong key is refused (403) - so check 1 was measuring the key, not luck"
} else {
    Fail "a WRONG KEY was not refused (HTTP $($r2.code)). The endpoint is open to anyone."
}

# 3. NEGATIVE CONTROL - something that is not a zip must be refused.
$notZip = [Text.Encoding]::ASCII.GetBytes("this is not a zip file at all")
$r3 = Post $notZip $uploadKey $null
if ($r3.code -eq 415) {
    Ok "a non-zip is refused (415)"
} else {
    Note "a non-zip returned HTTP $($r3.code), expected 415 - worth a look, not fatal"
}

# 4. THE ONE THAT PROTECTS CONTRIBUTORS' DATA. A declared hash that does not
#    match what arrived must be refused and stored nowhere - because the sender
#    clears its local copy on a match, and a receiver that agreed with a lie
#    would tell somebody it was safe to delete their only copy.
$r4 = Post $probeBytes $uploadKey ("0" * 64)
if ($r4.code -eq 409) {
    Ok "a mismatched hash is refused (409) and nothing is stored"
    Note "this is the check that stops a truncated upload clearing somebody's data"
} else {
    Fail "a WRONG HASH was accepted (HTTP $($r4.code)). A damaged upload could clear a contributor's only copy."
}

Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item $probeZip -Force -ErrorAction SilentlyContinue

# ---------------------------------------------------------------------------
# WHAT TO DO WITH IT
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "RECEIVING, AND PROVEN TO REFUSE WHAT IT SHOULD." -ForegroundColor Green
Write-Host ""
Write-Host "Put these two lines in collector-settings.txt:"
Write-Host ""
Write-Host "    send_url = $sendUrl" -ForegroundColor Cyan
Write-Host "    send_key = $uploadKey" -ForegroundColor Cyan
Write-Host ""
Write-Host "Then make a new package. The packager copies those two lines into it,"
Write-Host "so everyone you hand it to can send with one click - and check the log"
Write-Host "line, because a package built without them says so out loud."
Write-Host ""
Write-Host "To read what arrives:"
Write-Host "    wrangler r2 object get $BucketName/<key> --file out.zip"
Write-Host "    .\collector-master.exe --merge <folder of exports>"
Write-Host ""
Write-Host "One probe upload is in the bucket under uploads/deploy-probe/ - delete it"
Write-Host "whenever, it is a text file in a zip."
