/**
 * I1's NAMED CONTROL: with the network blocked, the hardpoint panel still fills.
 *
 * "Control, and it is the one that matters: with the network blocked after
 *  first load, the hardpoint panel still fills. Same control that proved H2."
 *
 * So the network is blocked properly rather than by hoping. Every network
 * global a browser would offer - fetch, XMLHttpRequest, WebSocket, EventSource,
 * navigator.sendBeacon - is replaced with something that THROWS on call, and
 * the harness then proves the poison is live by calling it itself and requiring
 * the throw. A "network blocked" test whose blocker is a no-op is exactly the
 * silent success this project keeps finding: it would pass for a page that
 * fetched happily.
 *
 * WHAT IS ACTUALLY UNDER TEST
 * ---------------------------
 * The panel's code AS SHIPPED. This does not re-implement it and does not read
 * a copy: it slices the block verbatim out of the BUILT testing/_deploy/
 * index.html, loads hardpoint_data.gen.js exactly as the page's <script src>
 * would, gives it the handful of browser globals it touches, and calls the real
 * loadHardpoints().
 *
 * STATED LIMIT, not glossed: this proves the panel's LOGIC and the HTML it
 * produces. It does not prove layout, CSS, or a browser's own enforcement of
 * anything. No browser is available on this machine and nothing was installed
 * to get one (rule 7). Same limit and same reason as _verify_find_page.mjs.
 *
 * THE FALLBACK IS OWNED BY checks/_verify_ship_hardpoint_panel.mjs, and only by
 * it. That suite runs this same shipped code with NO HP_DATA defined - which is
 * precisely the "the file did not load" case - and requires the API path and
 * every one of its failure sentences to behave exactly as they did before I1. A
 * second copy of those assertions here would drift from the first the moment
 * either was edited.
 *
 * --self-test inverts every expectation and must exit non-zero.
 *
 * Usage:  node checks/_verify_hardpoint_panel_offline.mjs [--self-test]
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const HERE = dirname(fileURLToPath(import.meta.url));
const DEPLOY = join(HERE, "..", "testing", "_deploy");
const PAGE = join(DEPLOY, "index.html");
const DATA = join(DEPLOY, "hardpoint_data.gen.js");
const SELFTEST = process.argv.includes("--self-test");

let passed = 0;
const failures = [];
function record(got, label, detail = "") {
  const want = SELFTEST ? !got : got;
  if (want) { passed++; console.log(`  ok   ${label}`); }
  else { failures.push(`${label} ${detail}`.trim()); console.log(`  FAIL ${label} ${detail}`); }
}

const page = readFileSync(PAGE, "utf8");
const dataJs = readFileSync(DATA, "utf8");

// ---- the shipped block, sliced by its own delimiters ---------------------
// Same slice _verify_ship_hardpoint_panel.mjs takes, for the same reason: what
// is tested has to be the built artifact, not the source it was built from.
const START = "/* ==========================================================================\n   G8 - the Loadout panel stops saying";
const END = 'const CC_DIR="../sc-ships/"';
const i = page.indexOf(START);
const j = page.indexOf(END, i);
if (i === -1 || j === -1) {
  console.log("NOT PERFORMED: could not find the panel block in the BUILT page. " +
              "Either build_deploy.py was not re-run, or the block was renamed. " +
              "Reported as not performed, never as passed.");
  process.exit(1);
}
const shipped = page.slice(i, j);

console.log("--- the file ships, and the page asks for it ---");
record(/<script src="hardpoint_data\.gen\.js"><\/script>/.test(page),
  "the built page loads hardpoint_data.gen.js");
record(/const HP_DATA=/.test(dataJs), "hardpoint_data.gen.js is in _deploy");
record(/GENERATED by build_hardpoint_data\.py/.test(dataJs),
  "and names the generator that wrote it");
record(!/generated at/i.test(dataJs.split("const HP_SCHEMA")[0]),
  "and carries no generation timestamp");

console.log("\n--- the fallback is still there, in the shipped bytes ---");
// I1 says in as many words: keep the API path as the fallback, and do not
// delete the honest failure message. Both are structural facts about the
// shipped code, so they are asserted on the shipped code.
record(/\/api\/v1\/ships\/models\//.test(shipped),
  "the API path is still in the page - it is the fallback, not deleted");
record(/The API did not answer, so nothing is shown rather than something/
  .test(shipped),
  "and its honest failure sentence is intact, word for word");
record(/This model is not in the hardpoint dataset yet/.test(shipped),
  "and so is the sentence for a model the dataset has never heard of");
record(/No hardpoint data for this hull/.test(shipped),
  "and the one for a hull we know and have no mounts for");

// -------------------------------------------- the sandbox, network poisoned
const NETWORK_ERROR = "NETWORK BLOCKED BY THE HARNESS - the panel touched it";
function poison(name) {
  return function blocked() {
    throw new Error(`${NETWORK_ERROR}: ${name}()`);
  };
}

const els = {
  "cc-slots": { innerHTML: "", textContent: "" },
  "cc-slotnote": { innerHTML: "", textContent: "" },
};

const sandbox = {
  console,
  URLSearchParams,
  encodeURIComponent,
  fetch: poison("fetch"),
  XMLHttpRequest: poison("XMLHttpRequest"),
  WebSocket: poison("WebSocket"),
  EventSource: poison("EventSource"),
  navigator: { sendBeacon: poison("navigator.sendBeacon"), onLine: false },
  location: { search: "" },
  $: (id) => els[id] || null,
};
vm.createContext(sandbox);
// `const HP_DATA = ...` inside a vm script is SCRIPT-scoped rather than a
// property of the context object, so it is loaded into the SAME context the
// panel runs in - which is exactly how the browser sees it, two <script> tags
// sharing one global scope.
vm.runInContext(dataJs, sandbox, { filename: "hardpoint_data.gen.js" });
vm.runInContext(shipped, sandbox, { filename: "index.html:panel" });
const g = (name) => vm.runInContext(name, sandbox);

console.log("\n--- THE POISON IS LIVE (a blocker that does not block is not one) ---");
let threw = false;
try { sandbox.fetch("http://example.invalid/"); } catch (e) {
  threw = e.message.includes(NETWORK_ERROR);
}
record(threw, "calling fetch() inside the sandbox throws, so 'network blocked' "
  + "means blocked");
let xhrThrew = false;
try { new sandbox.XMLHttpRequest(); } catch (e) {
  xhrThrew = e.message.includes(NETWORK_ERROR);
}
record(xhrThrew, "and so does XMLHttpRequest");
record(typeof sandbox.loadHardpoints === "function",
  "the panel's own code loaded and exposes loadHardpoints()");
record(g("HP_COUNTS") && g("HP_COUNTS").slots > 0,
  "the data file loaded and reports a slot count",
  `counts=${JSON.stringify(g("HP_COUNTS"))}`);

const slots = () => els["cc-slots"].innerHTML;
const note = () => els["cc-slotnote"].textContent;

async function run() {
  // ------------------------------------------- I1's control, in one block
  console.log("\n--- I1's NAMED CONTROL: the panel fills with the network blocked ---");
  await sandbox.loadHardpoints("600i Explorer");
  const filled = slots();
  record(/Countermeasures|Guns|Missile racks|Turrets and mounts/.test(filled),
    "a ship WITH slot data renders grouped mounts, from the file",
    filled.slice(0, 140));
  record(filled.length > 400, `and the panel is genuinely full (${filled.length} chars of markup)`);
  record(!/Could not reach|did not answer|Reading hardpoint data/.test(filled),
    "and no network-failure message and no stuck loading message appears");
  record(!/awaiting data/.test(filled), "and it does not say 'awaiting data'");
  record(/mounts, source:/.test(note()),
    "and the provenance note names the mount count and the source dataset",
    note().slice(0, 160));

  // The count on the page has to be the count in the database. HP_COUNTS is
  // the file's own statement of the total; the row count rendered here is what
  // a visitor actually sees. Compared against the model's own slot_count,
  // which build_hardpoint_data.py has already checked against PostgreSQL.
  const key = "600i explorer";
  const model = g("HP_DATA").models.find((m) => m[0] === key);
  const rendered = (filled.match(/class="cc-slot"(?! style)/g) || []).length;
  record(model && rendered === model[5].length,
    `every one of the hull's ${model ? model[5].length : "?"} mounts is rendered`,
    `rendered ${rendered}`);

  // ---- a hull we know about and have no mounts for ----------------------
  console.log("\n--- absence is data, and it is a different sentence ---");
  await sandbox.loadHardpoints("Kraken");
  const empty = slots();
  record(/No hardpoint data for this hull/.test(empty),
    "a hull with NO slot data shows an honest empty state", empty.slice(0, 160));
  record(/neither this model's name nor any mount-data key/.test(empty),
    "and it carries the BUILD'S OWN REASON, so the blank is explained");
  record(!/Reading hardpoint data/.test(empty), "and is not left on a spinner");
  record(!/(awaiting|pending|coming soon|TBD)/i.test(empty),
    "and it invents nothing to fill the space");

  // ---- a hull the dataset has never heard of ----------------------------
  await sandbox.loadHardpoints("Definitely Not A Ship");
  record(/not in the hardpoint dataset/.test(slots()),
    "an unknown model says so, answered from the file rather than by asking a "
    + "server to say the same thing slowly", slots().slice(0, 140));
  record(!/No hardpoint data for this hull/.test(slots()),
    "and it reads DIFFERENTLY from 'we have this hull but no mounts' - two "
    + "different facts, two different sentences");

  await sandbox.loadHardpoints("");
  record(/No model folder matched/.test(slots()),
    "a ship with no model folder says that, rather than looking up ''");

  // ---- the model_key rule ------------------------------------------------
  console.log("\n--- the page spells model_key the way the API does ---");
  // The API normalises with re.sub(r"[^a-z0-9]+", " ", raw.lower()).strip().
  // If the page's rule disagreed, hulls the API finds would come back "not in
  // the dataset" - a regression that looks exactly like missing data.
  //
  // `const CC_MODEL_KEY = ...` is SCRIPT-scoped inside a vm context rather than
  // a property of the sandbox object, so it is read by name in that context -
  // the same way the page's own code sees it.
  const CC_MODEL_KEY = g("CC_MODEL_KEY");
  record(CC_MODEL_KEY("600i Explorer") === "600i explorer",
    "a space-and-case name normalises");
  record(CC_MODEL_KEY("L-22 Alpha Wolf") === "l 22 alpha wolf",
    "a hyphen becomes a space");
  record(CC_MODEL_KEY("San'tok.yāi") === "san tok y i",
    "and so does an apostrophe, a dot and a non-ASCII letter - the same answer "
    + "the API's regex gives", CC_MODEL_KEY("San'tok.yāi"));
  await sandbox.loadHardpoints("santok yai");
  record(/not in the hardpoint dataset/.test(slots()),
    "a name that normalises to something the dataset does not hold is a miss, "
    + "not a crash");

  // ---- the source's own non-values are not displayed as values -----------
  console.log("\n--- two non-values the source spells as values ---");
  // 8 mounts state size 0; 167 state '<= PLACEHOLDER =>' as their stock item.
  // Both were rendered verbatim on the API path before I1. Neither is a value.
  await sandbox.loadHardpoints("HoverQuad");
  const hq = slots();
  record(hq.length > 100, "the HoverQuad's panel fills", hq.slice(0, 120));
  record(!/>S0</.test(hq),
    "no mount renders as 'S0' - an unstated size is omitted, never zeroed", hq);
  record(!/PLACEHOLDER/.test(hq),
    "and the game's '<= PLACEHOLDER =>' is not shown as a fitted component", hq);
  record(/not stated/.test(hq),
    "a mount left with nothing to say reads 'not stated' rather than blank");

  // And the suppression must be narrow. A control that hid everything would
  // pass both assertions above while destroying the panel.
  await sandbox.loadHardpoints("300i");
  const three = slots();
  record(/S\d/.test(three), "a hull with real sizes still shows them", three.slice(0, 200));
  record(/·|&middot;|·/.test(three) || /<span class="sv">[A-Za-z]/.test(three),
    "and real stock item names still appear - the suppression is narrow, not "
    + "a blanket");

  console.log("");
  if (failures.length) {
    console.log(`FAILED ${failures.length} of ${passed + failures.length}:`);
    failures.forEach((f) => console.log("  -", f));
    if (SELFTEST) {
      console.log("--self-test: expectations were inverted, so a non-zero exit "
        + "is the correct outcome.");
    }
    process.exit(1);
  }
  if (SELFTEST) {
    console.log("--self-test FAILED TO FAIL: every inverted expectation passed, "
      + "which means these assertions are not asserting anything.");
    process.exit(1);
  }
  console.log(`All ${passed} assertions passed, with every network global poisoned.`);
}

run().catch((e) => { console.log("FAILED:", e); process.exit(1); });
