/**
 * H3 / E2: does the DEPLOYED page actually hand a visitor real rows?
 *
 * THE RULE HAS NOT CHANGED JUST BECAUSE THE SOURCE DID. The MOCKUP banner
 * comes off only after fetching the deployed URL and reading real rows back
 * from it - not on a build, not on a deploy, not on a local server, not on a
 * good feeling. wrangler printing "Success" is an exit code, and this project
 * has already had one deploy report failure on a success and another publish
 * to an entirely different URL while reporting success.
 *
 * So: everything here comes over the wire from the deployed origin. Nothing is
 * read off local disk, and there is no fallback to a local copy - if the fetch
 * fails, that IS the answer and it is reported as a failure to verify rather
 * than as a pass.
 *
 * WHAT "REAL ROWS" MEANS HERE, stated so it cannot be quietly softened:
 * the page's own script, taken from the served bytes, driven against the
 * served data file, must render a named item at a named terminal with a
 * price in aUEC and the snapshot date on the row. A 200 with a plausible byte
 * count is not evidence - a mockup returns that too.
 *
 * --self-test inverts every expectation and must exit non-zero.
 *
 * Usage:  node checks/_verify_find_deployed.mjs [origin] [--self-test]
 */

import vm from "node:vm";

const args = process.argv.slice(2);
const SELFTEST = args.includes("--self-test");
const ORIGIN = (args.find(a => !a.startsWith("--"))
  || "https://citizencompasstesting.citizencompass-contact.workers.dev")
  .replace(/\/$/, "");

let passed = 0;
const failures = [];
function record(got, label, detail = "") {
  const want = SELFTEST ? !got : got;
  if (want) { passed++; console.log(`  ok   ${label}`); }
  else { failures.push(`${label} ${detail}`.trim()); console.log(`  FAIL ${label} ${detail}`); }
}

function die(why) {
  console.log("\n" + "=".repeat(62));
  console.log("NOT VERIFIED: " + why);
  console.log("This is reported as NOT PERFORMED, never as a pass. The banner");
  console.log("stays on.");
  process.exit(1);
}

async function get(path) {
  const url = ORIGIN + path;
  let response;
  try {
    response = await fetch(url, { headers: { "Cache-Control": "no-cache" } });
  } catch (e) {
    die(`fetching ${url} threw: ${e.message}`);
  }
  const body = await response.text();
  console.log(`  GET ${url}\n      -> HTTP ${response.status} ${response.statusText}, `
    + `${body.length} bytes, ${response.headers.get("content-type")}`);
  return { status: response.status, ok: response.ok, body };
}

console.log(`--- H3: fetching the DEPLOYED page at ${ORIGIN} ---`);
const page = await get("/find.html");
if (!page.ok) die(`/find.html answered HTTP ${page.status}`);
const data = await get("/find_data.gen.js");
if (!data.ok) die(`/find_data.gen.js answered HTTP ${data.status}`);

console.log("\n--- the served bytes are the new page, not a cached mockup ---");
record(/<script src="find_data\.gen\.js">/.test(page.body),
  "the served page loads the generated data file");
record(!/const SHOP\s*=/.test(page.body) && !/const ITEM\s*=/.test(page.body),
  "the invented SHOP / ITEM tables are not in the served bytes");
record(!/API_BASE/.test(page.body), "no API_BASE in the served bytes");
record(/GENERATED by build_find_data\.py/.test(data.body),
  "the served data file names its generator");

console.log("\n--- H3: what the SERVED page says about itself ---");
// Comments stripped, because the page's CSS carries a comment recording that
// the banner was removed and why. That note is the audit trail, not a banner.
const servedCode = page.body.replace(/\/\*[\s\S]*?\*\//g, "")
                            .replace(/^\s*\/\/.*$/gm, "");
record(!/MOCKUP/.test(servedCode),
  "the served page carries no MOCKUP banner");
record(!/prices and shops are invented/.test(page.body),
  "and not its wording either, comments included");
record(/id="srcbadge"/.test(page.body),
  "a provenance badge is served in its place");
record(/Cloud Imperium Rights LLC/.test(page.body),
  "and the trademark footer is intact on the served bytes (rule 8)");
record(/unofficial Star Citizen fan site/.test(page.body),
  "as is the Fan Kit disclaimer (rule 8)");

console.log("\n--- REAL ROWS, rendered by the SERVED script from the SERVED data ---");
let currentHash = "";
const view = { innerHTML: "" };
const qBox = { value: "", onkeydown: null, focus() {}, selectionStart: 0 };
const sandbox = {
  console, URLSearchParams, Date, Number, Math, String, Array, Object, Map, Set,
  JSON, RegExp, Error, isNaN, parseInt, parseFloat,
  encodeURIComponent, decodeURIComponent,
  addEventListener() {}, scrollTo() {},
  location: { get hash() { return currentHash; }, set hash(v) { currentHash = v; },
              search: "" },
  document: {
    activeElement: null,
    querySelector: s => (s === "#view" ? view : s === "#q" ? qBox : null),
    getElementById: id => (id === "view" ? view : id === "q" ? qBox : null),
  },
};
sandbox.window = sandbox;
sandbox.globalThis = sandbox;
vm.createContext(sandbox);

const script = page.body.match(/<script>([\s\S]*)<\/script>/);
if (!script) die("no inline <script> block in the served page");
vm.runInContext(data.body, sandbox, { filename: "served:find_data.gen.js" });
vm.runInContext(script[1], sandbox, { filename: "served:find.html" });
const g = name => vm.runInContext(name, sandbox);

function render(hash) {
  currentHash = "#" + hash;
  view.innerHTML = "";
  sandbox.route();
  return view.innerHTML;
}

const counts = g("FIND_COUNTS");
console.log(`      served data: ${counts.item_prices} price rows, `
  + `${counts.shop_items} items, ${counts.terminals} terminals`);
record(counts.item_prices > 20000,
  `the served data carries real price rows (${counts.item_prices})`);
record(counts.shop_items > 7000,
  `and real items (${counts.shop_items})`);

const item = render("i/item:1");
record(/Omnisky III Cannon/.test(item),
  "a real item renders from the served bytes");
record(/aUEC/.test(item), "with a real price in aUEC");
const rows = (item.match(/<tr class=/g) || []).length;
record(rows > 0, `at ${rows} named terminal${rows === 1 ? "" : "s"}`);
record(/UEX reported this in the snapshot taken/.test(item),
  "and every row states the snapshot it came from");
record(/20260801T235530Z/.test(item), "naming the actual snapshot key");
record(!/invented/i.test(item), "and the word 'invented' is nowhere in it");

const search = render("s/medpen");
record(/Medpen/i.test(search), "a search against the served data returns hits");
record(/result/.test(search), "and says how many");

const terminal = render("p/111");
record(/Ship Weapons/.test(terminal), "a terminal page renders from served data");
record(/Orison, Crusader, Stanton/.test(terminal), "with its resolved location");

console.log("\n" + "=".repeat(62));
if (SELFTEST) {
  console.log("--self-test: expectations were inverted, so a non-zero exit is");
  console.log("the correct outcome.");
}
if (failures.length) {
  console.log(`FAILED ${failures.length} of ${passed + failures.length}:`);
  failures.forEach(f => console.log("  -", f));
  console.log("\nThe banner STAYS ON.");
  process.exit(1);
}
console.log(`All ${passed} assertions passed against the DEPLOYED origin.`);
console.log(`Real rows came back from ${ORIGIN}.`);
